version: '3'

services:
  mysql:
    image: mysql:5
    container_name: mysql
    platform: linux/amd64
    ports: [ "3306:3306" ]
    volumes: [ "./db:/docker-entrypoint-initdb.d" ]
    environment: [ "MYSQL_ROOT_PASSWORD=root" ]
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-proot"
        ]
      timeout: 10s
      retries: 10
      start_period: 10s

  # api:
  #   build: .
  #   container_name: api
  #   environment:
  #     - "APP_PORT=3000"
  #     - "MYSQL_HOST=mysql"
  #     - "MYSQL_PORT=3306"
  #     - "MYSQL_USER=root"
  #     - "MYSQL_PASSWORD=root"
  #   ports: [ "3000:3000" ]
  #   depends_on:
  #     mysql:
  #       condition: service_healthy